language: php
php:
  - '7.0'
  - '7.1'

env:
  - SH=bash

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install bc -y

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit --verbose
  - bash -c "[ $(echo "$(grep '^  Lines' builds/coverage.txt | awk '{print $2;}' | tr -d '%') >= 75" | bc) -eq "1" ]"
